# This is a config for E2B sandbox template.
# You can use template ID (n71s3dmu45nc20appcp5) or template name (vibe-next-test-kislay-0007) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-next-test-kislay-0007") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-next-test-kislay-0007") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-next-test-kislay-0007')

team_id = "5f1a46dc-f981-493a-88f7-10d684d402b9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-next-test-kislay-0007"
template_id = "n71s3dmu45nc20appcp5"
