# This is a config for E2B sandbox template.
# You can use template ID (8ngtcyz3faxwin0eaksr) or template name (kislay-templat-vibe) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("kislay-templat-vibe") # Sync sandbox
# sandbox = await AsyncSandbox.create("kislay-templat-vibe") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('kislay-templat-vibe')

team_id = "5f1a46dc-f981-493a-88f7-10d684d402b9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "kislay-templat-vibe"
template_id = "8ngtcyz3faxwin0eaksr"
